### ISSUE TITLE
OOM Exception when operating large files

### ISSUE THREAD

**Issue by txnfail** [Pedrock/adjacent-cells#1]
<--- Last few GCs --->

[63823:0x103800000]     9297 ms: Mark-sweep 1355.0 (1413.8) -> 1355.0 (1413.8) MB, 57.6 / 0.0 ms  allocation failure GC in old space requested
[63823:0x103800000]     9372 ms: Mark-sweep 1355.0 (1413.8) -> 1355.0 (1412.8) MB, 61.3 / 0.0 ms  last resort GC in old space requested
[63823:0x103800000]     9449 ms: Mark-sweep 1355.0 (1412.8) -> 1355.0 (1412.8) MB, 77.6 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1b6fc2fa5729 <JSObject>
    0: builtin exit frame: parse(this=0x1b6fc2f88f59 <Object map = 0x1b6ffaa82ba1>,0x1b6f718a9331 <Uint8Array map = 0x1b6ffaac3c81>)

    1: /* anonymous */ [..../index.js:11] [bytecode=0x1b6f0387ff09 offset=109](this=0x1b6fafc65391 <Object map = 0x1b6ffaa823b9>,exports=0x1b6fafc65391 <Object map = 0x1b6ffaa823b9>,require=0x1b6fafc727...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 5: v8::internal::JsonParser<true>::ParseJsonArray() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 6: v8::internal::JsonParser<true>::ParseJsonValue() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 7: v8::internal::JsonParser<true>::ParseJsonArray() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 8: v8::internal::JsonParser<true>::ParseJsonValue() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
 9: v8::internal::JsonParser<true>::ParseJson() [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
10: v8::internal::Builtin_Impl_JsonParse(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/fonsecaj/.nvm/versions/node/v9.0.0/bin/node]
11: 0xcd40db0697d
[1]    63823 abort      node index.js ../../adjacent_cells/20000x20000.json

**Comment by Pedrock** [comment]
Hi,

The error happens in node's native json parsing method. This can be fixed by increasing node's memory limit by adding the following parameter when calling node:
```--max-old-space-size=4096```
I have updated the README with this information. I also updated the code in order to add a print function which outputs everything according to the expected format.

**Comment by txnfail** [comment]
@Pedrock, it would be great if the program could work with a memory footprint that's independent of the file size that it is processing.

**Comment by Pedrock** [comment]
@jaafonseca I believe that would only be possible by parsing the file manually and only loading the cells partially as they are required. Even in that case, the memory usage would still be somewhat dependent on the file size, since larger files can have larger groups. Is this a requirement?

Anyway, I've also changed the code to use a generator function, which reduces the memory usage since the generated groups can now be printed as soon as they are generated and without having to be stored in an array. This avoids a coupling between the solver class and the print function which would have been created if the results were to be printed inside the class.
With the new code I have been able to run the 20000x20000 file with a memory limit of 6144 MB.
EDIT: 4096 MB also works, but it seems to be slower due to the more aggressive garbage collection.

**Comment by Pedrock** [comment]
@jaafonseca I have updated the code to use a package for parsing the JSON as a stream. The Solver class is now a Duplex stream which receives the lines and outputs the groups as soon as each is complete.
There is no need to add the memory parameter now.

**Comment by txnfail** [comment]
nice! good work ;-)

**Comment by Pedrock** [comment]
@jaafonseca I hadn't tested the program until completion but the memory parameter is actually still required for the large files due to the large size of some groups. The memory requirement is not dependent on the size of the whole matrix, but it is dependent on its width and the groups it contains. A large matrix with small groups would not present memory problems.

**Comment by Pedrock** [comment]
@jaafonseca I had some bugs in the stream version which were causing some groups to be larger than expected. I have fixed the code and the memory parameter is not required for the 20000x20000 file after all.
